export const DISPLAY_ALERT = 'DISPLAY_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const LOGOUT_USER = 'LOGOUT_USER'

export const GET_TEST_BEGIN = 'GET_TEST_BEGIN'
export const GET_TEST_SUCCESS = 'GET_TEST_SUCCESS'
export const GET_TEST_ERROR = 'GET_TEST_ERROR'

export const ADD_TEST_BEGIN = 'ADD_TEST_BEGIN'
export const ADD_TEST_SUCCESS = 'ADD_TEST_SUCCESS'
export const ADD_TEST_ERROR = 'ADD_TEST_ERROR'